import { SxProps } from "@mui/material";

interface TypoStyles {
  [key: string]: SxProps;
}

export const typographyStyles: TypoStyles = {
  text32Bold: {
    fontFamily: "pretendard",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "150%",
  },
  text32Semibold: {
    fontFamily: "pretendard",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  text24Bold: {
    fontFamily: "pretendard",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "150%",
  },
  text24Semibold: {
    fontFamily: "pretendard",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  text24Medium: {
    fontFamily: "pretendard",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "140%",
    letterSpacing: "-0.22px",
  },
  text24Regular: {
    fontFamily: "pretendard",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
  text20Bold: {
    fontFamily: "pretendard",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "150%",
  },
  text20Semibold: {
    fontFamily: "pretendard",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  text20Medium: {
    fontFamily: "pretendard",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "150%",
  },
  text20Regular: {
    fontFamily: "pretendard",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
  text18Bold: {
    fontFamily: "pretendard",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "150%",
    "@media (min-width: 744px)": {
      fontFamily: "pretendard",
      fontSize: "18px",
      fontStyle: "normal",
      fontWeight: 700,
      lineHeight: "150%",
    },
  },
  text18Semibold: {
    fontFamily: "pretendard",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  text18Medium: {
    fontFamily: "pretendard",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "150%",
  },
  text18Regular: {
    fontFamily: "pretendard",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
  text16Bold: {
    fontFamily: "pretendard",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "150%",
  },
  text16Semibold: {
    fontFamily: "pretendard",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  text16Medium: {
    fontFamily: "pretendard",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "150%",
  },
  text16Regular: {
    fontFamily: "pretendard",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
  text14Bold: {
    fontFamily: "pretendard",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "150%",
  },
  text14Semibold: {
    fontFamily: "pretendard",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  text14Medium: {
    fontFamily: "pretendard",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "150%",
  },
  text14Regular: {
    fontFamily: "pretendard",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
  text13Semibold: {
    fontFamily: "pretendard",
    fontSize: "13px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  text13Medium: {
    fontFamily: "pretendard",
    fontSize: "13px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "150%",
  },
  text12Semibold: {
    fontFamily: "pretendard",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  text12Medium: {
    fontFamily: "pretendard",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "150%",
  },
  text12Regular: {
    fontFamily: "pretendard",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
};
